import type { Area } from "../types/area.service.type";
import type { Hotspot } from "../types/hotspots.service.type";
import type { Panorama } from "../types/panoramas.service.type";

export const BINHLONG_AREA: Area = {
  area_id: "1",
  area_name: "Phường Bình Long",
  domain: "vrapp-binhlong.vercel.app",
  main_hotspot_id: "1",
  description: "Bản đồ số Di tích Lịch sử Phường Bình Long, Tỉnh Bình Phước",
  is_active: true,
};

export const BINHLONG_HOTSPOTS: Hotspot[] = [
  {
    id: "1",
    hotspot_id: 1,
    area_id: 1,
    title: "Di tích Lịch sử Mộ 3.000 người An Lộc",
    description:
      "Nơi ghi dấu sự hy sinh anh dũng của hơn 3.000 đồng bào và chiến sĩ trong cuộc chiến đấu bảo vệ quê hương năm 1972. Di tích lịch sử - văn hóa cấp Quốc gia.",
    address: "Đường Lê Quý Đôn, Phường An Lộc, TX. Bình Long",
    website: null,
    geolocation: { lon: 106.6042, lat: 11.6483 },
    preview_image: "/landmarks/mo_3000_nguoi.jpg",
    click_panorama_id: "BinhLong_Mo3000DongBao",
    created_at: new Date().toISOString(),
    metadata: null,
    documents: null,
    assets: null,
  },
  {
    id: "2",
    hotspot_id: 2,
    area_id: 1,
    title: "Ngã Năm Thị Xã Bình Long",
    description:
      "Giao lộ huyết mạch lịch sử kết nối các tuyến đường trọng điểm của Bình Long, chứng nhân lịch sử qua các thời kỳ.",
    address: "Trung tâm Thị xã Bình Long, Tỉnh Bình Phước",
    website: null,
    geolocation: { lon: 106.6025, lat: 11.6455 },
    preview_image: "/landmarks/nga_nam_binh_long.jpg",
    click_panorama_id: "BinhLong_NgaNam",
    created_at: new Date().toISOString(),
    metadata: null,
    documents: null,
    assets: null,
  },
  {
    id: "3",
    hotspot_id: 3,
    area_id: 1,
    title: "Cổng chính Khu Di tích Mộ 3.000 người",
    description:
      "Cổng chính dẫn vào khuôn viên khu tưởng niệm Mộ tập thể 3.000 đồng bào An Lộc trang nghiêm và tôn kính.",
    address: "Đường Lê Quý Đôn, Phường An Lộc, TX. Bình Long",
    website: null,
    geolocation: { lon: 106.6045, lat: 11.6481 },
    preview_image: "/landmarks/mo_3000_nguoi.jpg",
    click_panorama_id: "BL_MO_CONGCHINH",
    created_at: new Date().toISOString(),
    metadata: null,
    documents: null,
    assets: null,
  },
  {
    id: "4",
    hotspot_id: 4,
    area_id: 1,
    title: "Cổng phụ & Cảnh quan Di tích",
    description:
      "Lối vào phụ và hoa viên xanh mát bao quanh khu di tích lịch sử tưởng niệm 3.000 đồng bào.",
    address: "Khuôn viên Di tích Mộ 3.000 người, TX. Bình Long",
    website: null,
    geolocation: { lon: 106.6048, lat: 11.6485 },
    preview_image: "/landmarks/binh_long_sunset.jpg",
    click_panorama_id: "BL_MO_CONGPHU",
    created_at: new Date().toISOString(),
    metadata: null,
    documents: null,
    assets: null,
  },
  {
    id: "5",
    hotspot_id: 5,
    area_id: 1,
    title: "Khuôn viên Nhà tưởng niệm",
    description:
      "Gian tưởng niệm trang nghiêm, lưu giữ các tư liệu, hình ảnh lịch sử về sự kiện Bình Long năm 1972.",
    address: "Nhà giữa Di tích Mộ 3.000 người, TX. Bình Long",
    website: null,
    geolocation: { lon: 106.6043, lat: 11.6484 },
    preview_image: "/landmarks/phat_quoc_van_thanh.jpg",
    click_panorama_id: "BL_MO_7_NHA_GIUA",
    created_at: new Date().toISOString(),
    metadata: null,
    documents: null,
    assets: null,
  },
];

export const BINHLONG_PANORAMAS: Panorama[] = [
  {
    panorama_id: "BinhLong_NgaNam",
    hotspot_id: 2,
    title: "Ngã Năm Bình Long",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BinhLong_Mo3000DongBao",
    hotspot_id: 1,
    title: "Mộ 3.000 Đồng Bào An Lộc",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_CONGCHINH",
    hotspot_id: 3,
    title: "Cổng chính di tích",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_CONGPHU",
    hotspot_id: 4,
    title: "Cổng phụ di tích",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_3",
    hotspot_id: 1,
    title: "Khuôn viên Mộ - Vị trí 3",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_5",
    hotspot_id: 1,
    title: "Khuôn viên Mộ - Vị trí 5",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_6",
    hotspot_id: 1,
    title: "Khuôn viên Mộ - Vị trí 6",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_7_NHA_GIUA",
    hotspot_id: 5,
    title: "Nhà tưởng niệm giữa",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_7_NHA_TRAI",
    hotspot_id: 5,
    title: "Nhà tưởng niệm bên trái",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_7_NHA_PHAI",
    hotspot_id: 5,
    title: "Nhà tưởng niệm bên phải",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_8",
    hotspot_id: 1,
    title: "Khuôn viên Mộ - Vị trí 8",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_9_GIUA",
    hotspot_id: 1,
    title: "Khu tưởng niệm - Giữa",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_9_TRAI",
    hotspot_id: 1,
    title: "Khu tưởng niệm - Trái",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_9_PHAI",
    hotspot_id: 1,
    title: "Khu tưởng niệm - Phải",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_10",
    hotspot_id: 1,
    title: "Khu tưởng niệm - Vị trí 10",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_11_TRAI",
    hotspot_id: 1,
    title: "Khu tưởng niệm - 11 Trái",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_11_PHAI",
    hotspot_id: 1,
    title: "Khu tưởng niệm - 11 Phải",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_12_TRAI",
    hotspot_id: 1,
    title: "Khu tưởng niệm - 12 Trái",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_12_PHAI",
    hotspot_id: 1,
    title: "Khu tưởng niệm - 12 Phải",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
  {
    panorama_id: "BL_MO_13",
    hotspot_id: 1,
    title: "Khu tưởng niệm - Vị trí 13",
    preview_image: "/vr_core/thumbnail.png",
    created_at: new Date().toISOString(),
  },
];
